image: node:9

cache:
  paths:
  - node_modules/

stages:
  - deploy
  
打包:
  stage: deploy
  script:
    - echo 'start'
    - yarn install --registry=https://registry.npm.taobao.org
    - npm run build
    - echo $(ls deploy)
    - npm run deploy
  only:
    - dev
  when: manual
  tags:
    - txy

