image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - deploy
  
打包:
  stage: deploy
  script:
    - echo 'start'
    - echo $(ls)
    - npm install --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist
    - npm run build

